table MTable
	lineageTag: 94196c8e-24bd-4132-b6c1-c8a7211b6c74

	measure user = USERPRINCIPALNAME()
		lineageTag: 359ce497-f5d1-48ad-894c-e522136eb124

	column Column1
		dataType: string
		lineageTag: a2ea3fcf-b301-413d-979d-277e71698681
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	partition MTable = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

